apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ecommerce-product-catalog
  labels:
    cloud.googleapis.com/location: asia-southeast1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
      - name: app
        image: asia-southeast1-docker.pkg.dev/heroic-night-453607-n0/ecommerce/product-catalog:cloud-run-v5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
        env:
        - name: DB_HOST
          value: "127.0.0.1"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "secretpassword"
      - name: mysql
        image: bitnami/mariadb:latest
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "secretpassword"
        - name: MARIADB_DATABASE
          value: "products"
